---
- hosts: all
  become: true

  roles:
    - role: prereqs
    - role: raspberrypi

- hosts: all
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - role: geerlingguy.swap
    - role: geerlingguy.containerd
    - role: geerlingguy.kubernetes
