---
- name: Ensure necessary kernel modules are loaded
  modprobe:
    name: '{{ item }}'
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Ensure necessary kernel modules load at boot
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure IP forwarding is enabled
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
